# Target platform
set(TARGET_PREFIX "src/target/stm32f103c6" CACHE STRING "")
set(TOOLCHAIN "gcc" CACHE STRING "")
set(GCC_TOOLCHAIN_PATH_PREFIX "" CACHE STRING "")
set(GCC_TOOLCHAIN_NAME_PREFIX "arm-none-eabi-" CACHE STRING "")
set(USE_STM32CUBEF1_LIBRARY ON CACHE BOOL "")
set(USE_STM32F103C6_TARGET ON CACHE BOOL "")
